# Our docker-compose file uses Dockerfile-dev instead of Dockerfile
FROM python:3.7
LABEL maintainer "Hryhorii Ohanisian <hryhorii.ohanisian@gmail.com>"

COPY . /app
WORKDIR /app
RUN pip install -r requirements.txt

ENV FLASK_ENV=docker
EXPOSE 5000